---
version: '0.1'

globalTimeout: 90
testSuiteTimeout: 90
testSuiteStep: 90

matrix:
  os: [mac]
  files: ["specs/google.spec.js","specs/lt.spec.js"]

runson: ${matrix.os}

pre:
  - npm install

cacheKey: '{{ checksum "package.json" }}'
cacheDirectories:
  - node_modules

mergeArtifacts: true
uploadArtifacts: 
    - name: Surefire Report
      path:
        - target/surefire-reports/**

report: true
partialReports:
  frameworkName: extent
  location: target/surefire-reports/html
  type: json

testSuites:
  - npm test -- $files

jobLabel: [puppeteer-Mocha, mac, matrix]